package cc.co.sarihh.antiinferencehub;

import org.jdesktop.application.Action;

public class AboutBox extends javax.swing.JDialog {

    public AboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    @Action
    public final void ok() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JTabbedPane();
        aboutPanel = new javax.swing.JPanel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        licensePanel = new javax.swing.JPanel();
        licenseScrollPane = new javax.swing.JScrollPane();
        licenseTextArea = new javax.swing.JTextArea();
        iconPanel = new javax.swing.JPanel();
        iconLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel iconLabel2 = new javax.swing.JLabel();
        iconLabel3 = new javax.swing.JLabel();
        thirdPanel = new javax.swing.JPanel();
        thirdScrollPane = new javax.swing.JScrollPane();
        thirdTextArea = new javax.swing.JTextArea();
        acknowledegmentPanel = new javax.swing.JPanel();
        acknowledegmentScrollPane = new javax.swing.JScrollPane();
        acknowledegmentTextArea = new javax.swing.JTextArea();
        southPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cc.co.sarihh.antiinferencehub.App.class).getContext().getResourceMap(AboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setName("centerPanel"); // NOI18N

        aboutPanel.setBackground(new java.awt.Color(255, 255, 255));
        aboutPanel.setName("aboutPanel"); // NOI18N
        aboutPanel.setLayout(new java.awt.BorderLayout());

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc/co/sarihh/antiinferencehub/resources/about.jpg"))); // NOI18N
        imageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imageLabel.setName("imageLabel"); // NOI18N
        aboutPanel.add(imageLabel, java.awt.BorderLayout.CENTER);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setName("infoPanel"); // NOI18N
        infoPanel.setLayout(new java.awt.BorderLayout());

        infoScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        infoScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoScrollPane.setName("infoScrollPane"); // NOI18N

        infoTextArea.setColumns(20);
        infoTextArea.setEditable(false);
        infoTextArea.setFont(new java.awt.Font("Arial", 0, 11));
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setText(resourceMap.getString("infoTextArea.text")); // NOI18N
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setName("infoTextArea"); // NOI18N
        infoTextArea.setSelectionColor(new java.awt.Color(212, 208, 200));
        infoTextArea.setCaretPosition(0);
        infoScrollPane.setViewportView(infoTextArea);

        infoPanel.add(infoScrollPane, java.awt.BorderLayout.CENTER);

        aboutPanel.add(infoPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.addTab(resourceMap.getString("aboutPanel.TabConstraints.tabTitle"), aboutPanel); // NOI18N

        licensePanel.setBackground(new java.awt.Color(255, 255, 255));
        licensePanel.setName("licensePanel"); // NOI18N
        licensePanel.setLayout(new java.awt.BorderLayout());

        licenseScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        licenseScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        licenseScrollPane.setName("licenseScrollPane"); // NOI18N

        licenseTextArea.setColumns(20);
        licenseTextArea.setEditable(false);
        licenseTextArea.setFont(new java.awt.Font("Arial", 0, 11));
        licenseTextArea.setLineWrap(true);
        licenseTextArea.setRows(5);
        licenseTextArea.setText(resourceMap.getString("licenseTextArea.text")); // NOI18N
        licenseTextArea.setWrapStyleWord(true);
        licenseTextArea.setName("licenseTextArea"); // NOI18N
        licenseTextArea.setSelectionColor(new java.awt.Color(212, 208, 200));
        licenseTextArea.setCaretPosition(0);
        licenseScrollPane.setViewportView(licenseTextArea);

        licensePanel.add(licenseScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.addTab(resourceMap.getString("licensePanel.TabConstraints.tabTitle"), licensePanel); // NOI18N

        iconPanel.setBackground(new java.awt.Color(255, 255, 255));
        iconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iconPanel.setName("iconPanel"); // NOI18N

        iconLabel1.setFont(new java.awt.Font("Arial", 0, 14));
        iconLabel1.setText(resourceMap.getString("iconLabel1.text")); // NOI18N
        iconLabel1.setName("iconLabel1"); // NOI18N

        iconLabel2.setBackground(new java.awt.Color(255, 255, 255));
        iconLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cc/co/sarihh/antiinferencehub/resources/java.jpg"))); // NOI18N
        iconLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconLabel2.setName("iconLabel2"); // NOI18N

        iconLabel3.setFont(new java.awt.Font("Arial", 0, 14));
        iconLabel3.setText(resourceMap.getString("iconLabel3.text")); // NOI18N
        iconLabel3.setName("iconLabel3"); // NOI18N

        javax.swing.GroupLayout iconPanelLayout = new javax.swing.GroupLayout(iconPanel);
        iconPanel.setLayout(iconPanelLayout);
        iconPanelLayout.setHorizontalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addGroup(iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iconPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(iconLabel1))
                    .addGroup(iconPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconLabel3))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        iconPanelLayout.setVerticalGroup(
            iconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iconPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(iconLabel1)
                .addGap(32, 32, 32)
                .addComponent(iconLabel2)
                .addGap(42, 42, 42)
                .addComponent(iconLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        centerPanel.addTab(resourceMap.getString("iconPanel.TabConstraints.tabTitle"), iconPanel); // NOI18N

        thirdPanel.setName("thirdPanel"); // NOI18N
        thirdPanel.setLayout(new java.awt.BorderLayout());

        thirdScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        thirdScrollPane.setName("thirdScrollPane"); // NOI18N

        thirdTextArea.setColumns(20);
        thirdTextArea.setEditable(false);
        thirdTextArea.setFont(new java.awt.Font("Arial", 0, 11));
        thirdTextArea.setLineWrap(true);
        thirdTextArea.setRows(5);
        thirdTextArea.setText(resourceMap.getString("thirdTextArea.text")); // NOI18N
        thirdTextArea.setWrapStyleWord(true);
        thirdTextArea.setName("thirdTextArea"); // NOI18N
        thirdTextArea.setSelectionColor(new java.awt.Color(212, 208, 200));
        licenseTextArea.setCaretPosition(0);
        thirdScrollPane.setViewportView(thirdTextArea);

        thirdPanel.add(thirdScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.addTab(resourceMap.getString("thirdPanel.TabConstraints.tabTitle"), thirdPanel); // NOI18N

        acknowledegmentPanel.setName("acknowledegmentPanel"); // NOI18N
        acknowledegmentPanel.setLayout(new java.awt.BorderLayout());

        acknowledegmentScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        acknowledegmentScrollPane.setName("acknowledegmentScrollPane"); // NOI18N

        acknowledegmentTextArea.setColumns(20);
        acknowledegmentTextArea.setEditable(false);
        acknowledegmentTextArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        acknowledegmentTextArea.setLineWrap(true);
        acknowledegmentTextArea.setRows(5);
        acknowledegmentTextArea.setText(resourceMap.getString("acknowledegmentTextArea.text")); // NOI18N
        acknowledegmentTextArea.setWrapStyleWord(true);
        acknowledegmentTextArea.setName("acknowledegmentTextArea"); // NOI18N
        acknowledegmentTextArea.setSelectionColor(new java.awt.Color(212, 208, 200));
        licenseTextArea.setCaretPosition(0);
        acknowledegmentScrollPane.setViewportView(acknowledegmentTextArea);

        acknowledegmentPanel.add(acknowledegmentScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.addTab(resourceMap.getString("acknowledegmentPanel.TabConstraints.tabTitle"), acknowledegmentPanel); // NOI18N

        centerPanel.setSelectedComponent(aboutPanel);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setBackground(new java.awt.Color(255, 255, 255));
        southPanel.setName("southPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cc.co.sarihh.antiinferencehub.App.class).getContext().getActionMap(AboutBox.class, this);
        okButton.setAction(actionMap.get("ok")); // NOI18N
        okButton.setBackground(new java.awt.Color(255, 255, 255));
        okButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 10)));
        okButton.setName("okButton"); // NOI18N
        okButton.setPreferredSize(new java.awt.Dimension(100, 21));
        southPanel.add(okButton);

        mainPanel.add(southPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-359)/2, (screenSize.height-424)/2, 359, 424);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JPanel acknowledegmentPanel;
    private javax.swing.JScrollPane acknowledegmentScrollPane;
    private javax.swing.JTextArea acknowledegmentTextArea;
    private javax.swing.JTabbedPane centerPanel;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel iconLabel3;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel licensePanel;
    private javax.swing.JScrollPane licenseScrollPane;
    private javax.swing.JTextArea licenseTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPanel thirdPanel;
    private javax.swing.JScrollPane thirdScrollPane;
    private javax.swing.JTextArea thirdTextArea;
    // End of variables declaration//GEN-END:variables
}
