package info.sarihh.antiinferencehub;

import org.jdesktop.application.Action;

public class AboutBox extends javax.swing.JDialog {

    public AboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    @Action
    public final void ok() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JTabbedPane();
        aboutPanel = new javax.swing.JPanel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        licensePanel = new javax.swing.JPanel();
        licenseScrollPane = new javax.swing.JScrollPane();
        licenseTextArea = new javax.swing.JTextArea();
        southPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(info.sarihh.antiinferencehub.App.class).getContext().getResourceMap(AboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setName("centerPanel"); // NOI18N

        aboutPanel.setBackground(new java.awt.Color(255, 255, 255));
        aboutPanel.setName("aboutPanel"); // NOI18N
        aboutPanel.setLayout(new java.awt.BorderLayout());

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info/sarihh/antiinferencehub/resources/about.jpg"))); // NOI18N
        imageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imageLabel.setName("imageLabel"); // NOI18N
        aboutPanel.add(imageLabel, java.awt.BorderLayout.CENTER);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setName("infoPanel"); // NOI18N
        infoPanel.setLayout(new java.awt.BorderLayout());

        infoScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        infoScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoScrollPane.setName("infoScrollPane"); // NOI18N

        infoTextArea.setColumns(20);
        infoTextArea.setEditable(false);
        infoTextArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setText(resourceMap.getString("infoTextArea.text")); // NOI18N
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setName("infoTextArea"); // NOI18N
        infoTextArea.setSelectionColor(new java.awt.Color(212, 208, 200));
        infoTextArea.setCaretPosition(0);
        infoScrollPane.setViewportView(infoTextArea);

        infoPanel.add(infoScrollPane, java.awt.BorderLayout.CENTER);

        aboutPanel.add(infoPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.addTab(resourceMap.getString("aboutPanel.TabConstraints.tabTitle"), aboutPanel); // NOI18N

        licensePanel.setBackground(new java.awt.Color(255, 255, 255));
        licensePanel.setName("licensePanel"); // NOI18N
        licensePanel.setLayout(new java.awt.BorderLayout());

        licenseScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        licenseScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        licenseScrollPane.setName("licenseScrollPane"); // NOI18N

        licenseTextArea.setColumns(20);
        licenseTextArea.setEditable(false);
        licenseTextArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        licenseTextArea.setLineWrap(true);
        licenseTextArea.setRows(5);
        licenseTextArea.setText(resourceMap.getString("licenseTextArea.text")); // NOI18N
        licenseTextArea.setWrapStyleWord(true);
        licenseTextArea.setName("licenseTextArea"); // NOI18N
        licenseTextArea.setSelectionColor(new java.awt.Color(212, 208, 200));
        licenseTextArea.setCaretPosition(0);
        licenseScrollPane.setViewportView(licenseTextArea);

        licensePanel.add(licenseScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.addTab(resourceMap.getString("licensePanel.TabConstraints.tabTitle"), licensePanel); // NOI18N

        centerPanel.setSelectedComponent(aboutPanel);

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        southPanel.setBackground(new java.awt.Color(255, 255, 255));
        southPanel.setName("southPanel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(info.sarihh.antiinferencehub.App.class).getContext().getActionMap(AboutBox.class, this);
        okButton.setAction(actionMap.get("ok")); // NOI18N
        okButton.setBackground(new java.awt.Color(255, 255, 255));
        okButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 10)));
        okButton.setName("okButton"); // NOI18N
        okButton.setPreferredSize(new java.awt.Dimension(100, 21));
        southPanel.add(okButton);

        mainPanel.add(southPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(359, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTabbedPane centerPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel licensePanel;
    private javax.swing.JScrollPane licenseScrollPane;
    private javax.swing.JTextArea licenseTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
}
